# Understanding Shapes and Dimensions in NumPy

NumPy is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

## 1. What is a NumPy Array?

A NumPy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

## 2. Creating NumPy Arrays

Let's start by creating some arrays.

In [1]:
import numpy as np

# A 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print('1D Array:\n', arr1d)

# A 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print('\n2D Array:\n', arr2d)

# A 3D array
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print('\n3D Array:\n', arr3d)

1D Array:
 [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## 3. Understanding Shape and Dimension

The shape of an array is the number of elements in each dimension, and the dimension is the number of axes (or ranks) the array has.

In [2]:
# Shape and dimension of 1D array
print('Shape of 1D array:', arr1d.shape)
print('Dimension of 1D array:', arr1d.ndim)

# Shape and dimension of 2D array
print('\nShape of 2D array:', arr2d.shape)
print('Dimension of 2D array:', arr2d.ndim)

# Shape and dimension of 3D array
print('\nShape of 3D array:', arr3d.shape)
print('Dimension of 3D array:', arr3d.ndim)

Shape of 1D array: (5,)
Dimension of 1D array: 1

Shape of 2D array: (2, 3)
Dimension of 2D array: 2

Shape of 3D array: (2, 2, 2)
Dimension of 3D array: 3


## 4. Visualizing Shapes and Dimensions

To better understand shapes and dimensions, let's visualize them:

1. **1D Array**: Shape `(5,)`, Dimension `1`
   - Represents 5 elements in a single row or column.

2. **2D Array**: Shape `(2, 3)`, Dimension `2`
   - Represents a table with 2 rows and 3 columns.

3. **3D Array**: Shape `(2, 2, 2)`, Dimension `3`
   - Think of it as a cube, with each dimension representing a different axis in 3D space.

## Conclusion

Understanding the shape and dimension of arrays in NumPy is crucial for manipulating and operating on data in Python. With this knowledge, you can effectively handle and process multi-dimensional data for various applications in data science and machine learning.


## 5. Understanding `(5,)` vs `(1, 5)`

In NumPy, `(5,)` represents the shape of a one-dimensional array with 5 elements, whereas `(1, 5)` represents the shape of a two-dimensional array with 1 row and 5 columns.

### Example of `(5,)` vs `(1, 5)`

In [3]:
# Creating a 1D array with shape (5,)
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array (5,):\n", arr_1d)
print("Shape:", arr_1d.shape)

# Reshaping to a 2D array with shape (1, 5)
arr_2d = arr_1d.reshape(1, 5)
print("\n2D array (1, 5):\n", arr_2d)
print("Shape:", arr_2d.shape)

1D array (5,):
 [1 2 3 4 5]
Shape: (5,)

2D array (1, 5):
 [[1 2 3 4 5]]
Shape: (1, 5)


## 6. Manipulating Array Shapes

Arrays can be reshaped and transposed to change their shape and dimension. This is often required in data processing and machine learning.


### Reshaping Arrays

# Reshaping an array to a different shape
reshaped_array = arr_1d.reshape(5, 1)
print("Reshaped array (5, 1):\n", reshaped_array)

### Transposing Arrays

# Transposing an array (switching rows and columns)
transposed_array = reshaped_array.T
print("Transposed array:\n", transposed_array)

## 7. Practical Use in Machine Learning

In machine learning, it is common to reshape data to fit the requirements of different algorithms. For example, converting a row of labels into columns (or vice versa) is necessary to match the expected input format of a model or a function.


### Example: Preparing Labels for a Machine Learning Model

In [4]:
# Labels as a 1D array
labels = np.array([0, 1, 2, 3, 4])
print("Original labels:\n", labels)

# Reshaping labels to a 2D array with one column
labels_reshaped = labels.reshape(-1, 1)
print("\nReshaped labels:\n", labels_reshaped)

Original labels:
 [0 1 2 3 4]

Reshaped labels:
 [[0]
 [1]
 [2]
 [3]
 [4]]


In this example, reshaping the labels from a 1D array to a 2D array with a single column is often required by machine learning libraries, which expect inputs in a specific format. This manipulation ensures compatibility and correct processing of the data.